#!/bin/bash

# wget -O - https://raw.githubusercontent.com/pyPTV/url/master/proxy | bash



# Update the package list
sudo apt update

# Install Squid with OpenSSL support and apache2-utils
sudo apt install squid-openssl apache2-utils -y

# Backup the original Squid configuration file
sudo cp /etc/squid/squid.conf /etc/squid/squid.conf.backup

# Create a directory for the SSL certificate
sudo mkdir -p /etc/squid/ssl_cert
sudo chmod 700 /etc/squid/ssl_cert

# Generate a self-signed certificate
sudo openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/squid/ssl_cert/myCA.pem -out /etc/squid/ssl_cert/myCA.pem
sudo chmod 400 /etc/squid/ssl_cert/myCA.pem

# Create and initialize the SSL db directory
sudo mkdir -p /var/spool/squid/ssl_db
sudo /usr/lib/squid/security_file_certgen -c -s /var/spool/squid/ssl_db -M 4MB
sudo chown -R proxy:proxy /var/spool/squid/ssl_db

# Squid configuration with SSL support and fixed port 8080
echo "
http_port 8080 ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/etc/squid/ssl_cert/myCA.pem
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
auth_param basic children 5
auth_param basic realm Squid proxy-caching web server
auth_param basic credentialsttl 1 year
auth_param basic casesensitive off
acl SSL_ports port 443
acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump bump all
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
" | sudo tee /etc/squid/squid.conf

# Generate random username and password
PROXY_USER=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
PROXY_PASS=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')

# Create the password file with the first user (it will overwrite existing file!)
sudo htpasswd -b -c /etc/squid/passwd $PROXY_USER $PROXY_PASS

# Restart Squid to apply the changes
sudo systemctl restart squid

# Enable Squid to start on boot
sudo systemctl enable squid

# Retrieve server IP address
SERVER_IP=$(hostname -I | awk '{print $1}')

# Print the filled proxy details
echo "
proxies = {
    'http': 'http://$PROXY_USER:$PROXY_PASS@$SERVER_IP:8080',
    'https': 'http://$PROXY_USER:$PROXY_PASS@$SERVER_IP:8080'
}
"

# End of script
