#!/bin/bash

apt install git build-essential -y
apt install zlib1g-dev -y
apt install libpcre3-dev libpcre++-dev -y
apt install openssl -y
apt install libssl-dev -y
apt install zlibc -y
apt install libgeoip-dev -y
wget http://nginx.org/download/nginx-1.12.2.tar.gz
tar zxf nginx-1.12.2.tar.gz
cd nginx-1.12.2
./configure --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log  --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-pcre-jit --with-http_gzip_static_module --with-http_ssl_module --without-http_browser_module --with-http_geoip_module --without-http_memcached_module --without-http_referer_module --without-http_scgi_module --without-http_split_clients_module --with-http_stub_status_module --without-http_ssi_module --without-http_userid_module --without-http_uwsgi_module --with-http_mp4_module --with-http_slice_module
make
make install
mv /etc/nginx/sbin/nginx /usr/sbin/nginx
rm -r -f /etc/nginx/sbin


cd /etc/nginx
wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
gunzip GeoIP.dat.gz
echo "geoip_country /etc/nginx/GeoIP.dat;" > /etc/nginx/conf.d/geoip.conf

wget https://raw.githubusercontent.com/mbs-affiliate/url/master/reverse_nginx /etc/nginx/sites-available/
rm -f /etc/nginx/sites-available/default

apt install bind9 dnsutils
